language: php

php:
  - '7.1'

services:
  - mysql

env:
  - SYMFONY_ENV=dev

before_script:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest

script:
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - vendor/bin/codecept run
