before_script:
  - docker-compose up -d
  - docker-compose exec app composer install --no-progress --no-interaction --prefer-dist --no-suggest

script:
  - docker-compose exec app php bin/console doctrine:migrations:migrate -n
  - docker-compose exec app php bin/console doctrine:fixtures:load -n
  - docker-compose exec app vendor/bin/codecept run
