version: "3"

services:
  app:
    image: webdevops/php-apache:7.1
    ports:
      - "85:80"
    depends_on:
      - db
    environment:
      WEB_DOCUMENT_ROOT: /srv/web
      WEB_DOCUMENT_INDEX: app.php
      PHP_DATE_TIMEZONE: "UTC"
    working_dir: /srv
    volumes:
      - .:/srv

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gwenvael_dronka
      MYSQL_USER: gwenvael
      MYSQL_PASSWORD: gwenvael
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3305:3306"
