<?php

namespace AppBundle\Repository;

/**
 * PageDispositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageDispositionRepository extends \Doctrine\ORM\EntityRepository
{
}
