image:
    resource: '@AppBundle/Controller/ImageController.php'
    type: annotation

admin:
    resource: "@AppBundle/Controller/Admin"
    type: annotation
    prefix: /admin

website:
    resource: '@AppBundle/Controller/Website'
    type: annotation
