parameters:
    env(DATABASE_HOST): db
    env(DATABASE_PORT): null
    env(DATABASE_NAME): gwenvael_dronka
    env(DATABASE_USER): gwenvael
    env(DATABASE_PASSWORD): gwenvael

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
twig:
    form_themes: ['bootstrap_3_horizontal_layout.html.twig']
